### ISSUE TITLE
what's the difference with https://github.com/AI-liu/Complex-YOLO?!

### ISSUE THREAD

**Issue by MingmingWarm** [Yuanchu/YOLO3D#1]
Hey ,guy. what's the difference with https://github.com/AI-liu/Complex-YOLO?!  I didn't found ...

**Comment by wl5** [comment]
This serves as our baseline implementation (see citation in readme).  We will work to improve in terms of both theory and implementation later on, possibly by adding map back to 3D and Bernoulli masks.
