### ISSUE TITLE
ValueError: cannot copy sequence with size 8 to array axis with dimension 7

### ISSUE THREAD

**Issue by jediofgever** [Yuanchu/YOLO3D#2]
Hi , Thank you for your contribution. I wanted to train the network with main.py. I changed datset directory and other steps that are in readme file. However When I run python main.py , I encounter problem in title. The whole output is as follows ;

`atas@atas-Veriton-M4630G:~/YOLO3D$ python main.py 
`
`
Traceback (most recent call last):
`
`
File "main.py", line 69, in <module>
    loss = region_loss(output,target, loss_history, epoch, batch_idx)
`

`
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
`

`
  File "/home/atas/YOLO3D/region_loss.py", line 217, in forward
    loss_history[epoch, batch_idx, :] = [loss_x, loss_y, loss_w, loss_l, loss_conf, loss_cls, loss_Euler, loss_iou]
`

`
ValueError: cannot copy sequence with size 8 to array axis with dimension 7
`

I have changed batch size because my GPU is not that powerful to take 12 batch. My envoirment is ;
python2.7 
torch version; 1.0.0

Thank you for your help

**Comment by Yuanchu** [comment]
Thanks for using it and bringing the issue to my attention. The bug has now been fixed.

**Comment by jediofgever** [comment]
Could you please adress what was causing ?

**Comment by Yuanchu** [comment]
Error was exactly as the message reported: 

ValueError: cannot copy sequence with size 8 to array axis with dimension 7

loss_history was initialized in main.py to have length 7 but line 217 is trying to pass 8 variables. 

The code base is not in its cleanest mode right now, including lots of repetitive functions/methods. We plan to clean it up during the coming weeks.

**Comment by jediofgever** [comment]
I see , anyway it is a great resource , thank you for your fast reply.
